export { default as ProjetDashboard } from './ProjetDashboard.vue'
export { default as ProjetList } from './ProjetList.vue'
export { default as ProjetForm } from './ProjetForm.vue'
export { default as ProjetDetail } from './ProjetDetail.vue'
export { default as ProjetFormModal } from './ProjetFormModal.vue'
export { default as AddMemberModal } from './AddMemberModal.vue'
export { default as EditMemberModal } from './EditMemberModal.vue'